apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
  # DB_HOST: db-dev.daws78s.online
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # pod definition
# pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port